site_name: Aeternity Sophia
extra_css: [extra.css]
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - erlang
        
nav:
    - 'The sophia language' : 'index.md'
    - Syntax : 'syntax.md'
    - Contracts : 'contracts.md'
    - 'Standard Library Functions' : 'sophia_stdlib.md' 
    - Examples : 'examples.md'

repo_name: 'nikita-fuchs/sophiadocs'
repo_url: 'https://github.com/nikita-fuchs/sophiadocs'